apiVersion: v1
kind: Secret
metadata:
  name: agent-kyc-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MODEL_API_KEY: "{{ .Values.secrets.MODEL_API_KEY }}"
  DB_PASSWORD: "{{ .Values.secrets.DB_PASSWORD }}"