apiVersion: v1
kind: Secret
metadata:
  name: agent-kyc-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- if .Values.secret.otelEndpoint }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.secret.otelEndpoint | b64enc }}
  {{- end }}
