namespace: agent-sat
replicaCount: 2

image:
  repository: ghcr.io/hcmarella/agent-kyc
  tag: dev-7b16673
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

env:
  ENV_NAME: sat
  LOG_LEVEL: info