namespace: agent-prod
replicaCount: 2

image:
  repository: agent-kyc
  tag: local
  pullPolicy: Never

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

env:
  ENV_NAME: prod
  LOG_LEVEL: warn
  OTEL_SERVICE_NAME: agent-kyc-prod
  OTEL_EXPORTER_OTLP_ENDPOINT: ""

secrets:
  MODEL_API_KEY: dummy-local-key
  DB_PASSWORD: dummy-local-password