namespace: agent-sit
replicaCount: 1

image:
  repository: agent-kyc-sit
  tag: local
  pullPolicy: Never

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

env:
  ENV_NAME: sit
  LOG_LEVEL: info