namespace: agent-dev
replicaCount: 1

image:
  repository: ghcr.io/hcmarella/agent-kyc
  tag: dev-9e234d1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

env:
  ENV_NAME: dev
  LOG_LEVEL: debug
  OTEL_SERVICE_NAME: agent-kyc-dev
  OTEL_EXPORTER_OTLP_ENDPOINT: ""

secrets:
  MODEL_API_KEY: dummy-local-key
  DB_PASSWORD: dummy-local-password