namespace: agent-dev
replicaCount: 1
image:
  repository: ghcr.io/hcmarella/agent-kyc
  tag: dev-7b16673
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
  targetPort: 8000
env:
  ENV_NAME: dev
  LOG_LEVEL: debug
